import Head from "next/head";

import Search from "components/Search";

import LayoutStyles from "styles/Layout.module.scss";

const Home = () => {
  return (
    <>
      <Head>
        <title>DBK FE Tech Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={LayoutStyles.header}>
        <Search />
      </header>

      <main className={LayoutStyles.main}></main>
    </>
  );
};

export default Home;
